force-app/main/default/objects/Error_Log__c/fields/Job_Scope__c.field-meta.xml
<CustomField>
    <fullName>Job_Scope__c</fullName>
    <description>The Record IDs that are in scope</description>
    <inlineHelpText>The Record IDs that are in scope</inlineHelpText>
    <label>Job Scope</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Exception Message</description>
    <inlineHelpText>Exception Message</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>Stacktrace__c</fullName>
    <description>Exception Stacktrace</description>
    <inlineHelpText>Exception Stacktrace</inlineHelpText>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BatchApexErrorEventTriggerHandler.cls
public with sharing class BatchApexErrorEventTriggerHandler {
    public BatchApexErrorEventTriggerHandler() {

    }

    public void handleBatchApexErrorEvent(List<BatchApexErrorEvent> events) {
        // Handle the Batch Apex Error Event
        System.debug('Batch Apex Error Event: ' + events);

        for(BatchApexErrorEvent event : events) {
            // You can add your custom logic here to handle the error
            // For example, you might want to log the error or send a notification

            Error_Log__c errorLog = new Error_Log__c();
            errorLog.Name = 'Batch Apex Error';
            errorLog.Async_Apex_Job_Id__c = event.AsyncApexJobId;
            errorLog.Message__c = event.Message;
            errorLog.Stacktrace__c = event.StackTrace;
            errorLog.Job_Scope__c = event.JobScope;
            insert errorLog;
        }
        
    }

}