force-app/main/default/objects/Certification__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is the certification Active?</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <description>Certification related to the contact</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>contact for certification</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <description>Date of certification issue</description>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CredentialVerificationServiceTest.cls
@isTest
private class CredentialVerificationServiceTest {

    @TestSetup
    static void makeData(){
        Contact con = new Contact(LastName = 'DoeCredentialVerificationServiceTest',
                                  FirstName = 'John',
                                  Email = 'DoeCredentialVerificationServiceTest@mail.com');
        insert con;

        Certification__c cert = new Certification__c(Name = 'Test Certification', isActive__c = true);
        insert cert;

        Contact_Certification__c cc = new Contact_Certification__c(Contact__c = con.Id, Certification__c = cert.Id, isActive__c = true, Issue_Date__c = Date.today().addYears(-1));
        insert cc;
    }

    @IsTest
    static void testVerifyCredential() {

        Contact_Certification__c cc = [SELECT Id,Name FROM Contact_Certification__c WHERE Contact__r.LastName = 'DoeCredentialVerificationServiceTest' LIMIT 1];

        Test.startTest();
        String result = CredentialVerificationService.verifyCredential('DoeCredentialVerificationServiceTest', cc.Name);
        Test.stopTest();

        System.assertEquals('Valid', result);
    }

    @IsTest
    static void testVerifyCredentialContactNotFound() {

        Test.startTest();
        String result = CredentialVerificationService.verifyCredential('JessicaCredentialVerificationServiceTest', 'Test Certification');
        Test.stopTest();

        System.assertEquals('No record found', result);
    }

    @IsTest
    static void testVerifyCredentialRenewal() {

        Contact_Certification__c cc = [SELECT Id,Name FROM Contact_Certification__c WHERE Contact__r.LastName = 'DoeCredentialVerificationServiceTest' LIMIT 1];
        cc.isActive__c = false;
        update cc;

        Test.startTest();
        String result = CredentialVerificationService.verifyCredential('DoeCredentialVerificationServiceTest', cc.Name);
        Test.stopTest();

        System.assertEquals('Needs Renewal', result);
    }
}