force-app/main/default/objects/Certification__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is the certification Active?</description>
    <label>isActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Certification__c.field-meta.xml
<CustomField>
    <fullName>Certification__c</fullName>
    <description>Certification related to the contact</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>contact for certification</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Certifications</relationshipLabel>
    <relationshipName>Contact_Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Certification__c/fields/Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date__c</fullName>
    <description>Date of certification issue</description>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CredentialVerificationService.cls
global class CredentialVerificationService {

    webservice static String verifyCredential(String lastName, String certName) {

        Map<String, Contact_Certification__c> certMap = new Map<String, Contact_Certification__c>();
        for(Contact_Certification__c cert : [
            SELECT Id, Name, Contact__c, Certification__c, isActive__c, Certification__r.Name, Issue_Date__c
            FROM Contact_Certification__c
            WHERE Contact__r.LastName = :lastName
        ]) {
            certMap.put(cert.Name.toLowerCase(), cert);
        }

        if( certMap.isEmpty()) {
            return 'No record found';
        }

        if( certMap.containsKey(certName.toLowerCase()) && certMap.get(certName.toLowerCase()).isActive__c ) {
            return 'Valid';
        }

        return 'Needs Renewal';
    }
}